# Generated by Django 3.1.6 on 2021-02-04 03:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PateintUser',
            new_name='PatientUser',
        ),
        migrations.RenameField(
            model_name='patientuser',
            old_name='pateint_user',
            new_name='patient_user',
        ),
    ]
