# Generated by Django 3.1.6 on 2021-02-04 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0002_auto_20210203_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientuser',
            old_name='patient_user',
            new_name='reg_user',
        ),
        migrations.RenameField(
            model_name='staffuser',
            old_name='staff_user',
            new_name='reg_user',
        ),
    ]
