# Generated by Django 3.1.6 on 2021-02-09 03:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, unique=True)),
                ('location', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dob', models.DateTimeField(blank=True)),
                ('doj', models.DateTimeField(default=datetime.datetime(2021, 2, 8, 22, 42, 55, 539186))),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('specialist', models.CharField(default='None', max_length=100)),
                ('surgeon', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_doctor', to='HMS.department')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorPatientRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_doctor', to='HMS.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=68)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.PositiveBigIntegerField(blank=True, null=True)),
                ('medical_file', models.FileField(upload_to='medicalfile')),
                ('dob', models.DateField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('doctor', models.ManyToManyField(through='HMS.DoctorPatientRelation', to='HMS.Doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctorpatientrelation',
            name='patient_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_patient', to='HMS.patient'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorpatientrelation',
            unique_together={('doctor_to', 'patient_to')},
        ),
    ]
