# Generated by Django 3.1.6 on 2021-02-10 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medical_file',
        ),
        migrations.AddField(
            model_name='doctorpatientrelation',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorpatientrelation',
            name='medical_file',
            field=models.FileField(default='medicalfile/test.txt', upload_to='medicalfile'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doj',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 23, 6, 25, 374317)),
        ),
    ]
