# Generated by Django 3.1.6 on 2021-02-12 21:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0002_auto_20210209_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpatientrelation',
            name='date_last_visit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doj',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 12, 16, 35, 36, 373831)),
        ),
        migrations.AlterField(
            model_name='doctorpatientrelation',
            name='doctor_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_doctor', to='HMS.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='doctorpatientrelation',
            name='patient_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_patient', to='HMS.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.PositiveBigIntegerField(blank=True, max_length=10, null=True),
        ),
    ]
